// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFirstFolderWithImages(arg1) {
  return window['go']['main']['App']['FindFirstFolderWithImages'](arg1);
}

export function FindNextFolder(arg1, arg2) {
  return window['go']['main']['App']['FindNextFolder'](arg1, arg2);
}

export function FindPrevFolder(arg1, arg2) {
  return window['go']['main']['App']['FindPrevFolder'](arg1, arg2);
}

export function FindRandomFolderWithImages(arg1) {
  return window['go']['main']['App']['FindRandomFolderWithImages'](arg1);
}

export function GetFolderInfo(arg1) {
  return window['go']['main']['App']['GetFolderInfo'](arg1);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function ListSubfolders(arg1) {
  return window['go']['main']['App']['ListSubfolders'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
