// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function ListSubfolders(arg1) {
  return window['go']['main']['App']['ListSubfolders'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
