// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// Define the Folder type mirroring the Go struct
export interface Folder {
  name: string;
  path: string;
  children?: Folder[];
}

export function Greet(arg1: string): Promise<string>;

export function ListImages(arg1: string): Promise<Array<string>>;

export function ListSubfolders(arg1: string): Promise<Folder>;

export function ReadImage(arg1: string): Promise<string>;

export function SelectFolder(): Promise<string>;
