// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function ListImages(arg1:string):Promise<Array<string>>;

export function ListSubfolders(arg1:string):Promise<fs.Folder>;

export function ReadImage(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
